name: BUG 提交
description: 提交 Bug 反馈
title: 'bug:'
labels: [bug]
body:
  - type: markdown
    id: preface
    attributes:
      value: |
        感谢你花时间填写此错误报告！在开始之前，我们非常推荐阅读一遍[《开源最佳实践》](https://github.com/LinuxSuRen/open-source-best-practice)，这会在很大程度上提高我们彼此的效率。
  - type: markdown
    id: environment
    attributes:
      value: "## 环境信息"
  - type: input
    id: halo-version
    validations:
      required: false
    attributes:
      label: "是什么 Halo 版本出现了此问题？"
      description: "可以在管理后台的关于页面中找到。"
  - type: input
    id: plugin-version
    validations:
      required: false
    attributes:
      label: "使用的微信公众号同步插件版本是多少？"
      description: "可以在插件 `plugin.yaml` 文件中找到。"
  - type: markdown
    id: details
    attributes:
      value: "## 详细信息"
  - type: textarea
    id: what-happened
    attributes:
      label: "BUG 内容"
      description: "较详细的描述 BUG 导致了什么问题。"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "相关日志输出"
      description: "建议安装“Log Viewer”插件，在控制台 - 概览 - 日志 中复制主要日志内容，粘贴后会自动格式化为代码，因此无需反引号。"
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: "附加信息"
      description: "如果你还有其他需要提供的信息，可以在这里填写（可以提供截图、视频等）。"
